//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enesatac_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Authors()
        {
            this.Articles = new HashSet<Articles>();
        }
    
        public int Auther_Id { get; set; }
        public string Author_Name { get; set; }
        public string Author_Surname { get; set; }
        public string Author_Mail { get; set; }
        public string Author_Description { get; set; }
        public string Author_Password { get; set; }
        public string Author_Nickname { get; set; }
        public string Author_PictureUrl { get; set; }
        public string Author_Article_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articles> Articles { get; set; }
    }
}
