//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enesatac_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKEditor_Images
    {
        public int CKEditor_Id { get; set; }
        public string CKEditor_Url { get; set; }
    }
}
