//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enesatac_site.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnesAtac_DBEntities : DbContext
    {
        public EnesAtac_DBEntities()
            : base("name=EnesAtac_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Categorys> Categorys { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Log_Records> Log_Records { get; set; }
        public virtual DbSet<Sliders> Sliders { get; set; }
        public virtual DbSet<Comments> CommentsSet { get; set; }
        public virtual DbSet<CKEditor_Images> CKEditor_Images { get; set; }
    }
}
